# Generated by Django 3.1.7 on 2021-03-08 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ACT', 'Aktywny'), ('INACT', 'Nieaktywny od'), ('OFF', 'Niedostępny'), ('NTISS', 'Ktos ma problemy z internetem')], default='OFF', max_length=20)),
                ('last_reaction_time', models.IntegerField()),
                ('event', models.CharField(max_length=255)),
                ('page', models.CharField(max_length=1000)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses ',
            },
        ),
    ]
